apiVersion: v1
data:
  shibboleth2.xml: "<SPConfig xmlns=\"urn:mace:shibboleth:2.0:native:sp:config\"\n
    \   xmlns:conf=\"urn:mace:shibboleth:2.0:native:sp:config\"\n    xmlns:saml=\"urn:oasis:names:tc:SAML:2.0:assertion\"\n
    \   xmlns:samlp=\"urn:oasis:names:tc:SAML:2.0:protocol\"    \n    xmlns:md=\"urn:oasis:names:tc:SAML:2.0:metadata\"\n
    \   clockSkew=\"180\">\n\n    <!--\n    By default, in-memory StorageService,
    ReplayCache, ArtifactMap, and SessionCache\n    are used. See example-shibboleth2.xml
    for samples of explicitly configuring them.\n    -->\n\n    <!--\n    To customize
    behavior for specific resources on Apache, and to link vhosts or\n    resources
    to ApplicationOverride settings below, use web server options/commands.\n    See
    https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPConfigurationElements
    for help.\n    \n    For examples with the RequestMap XML syntax instead, see
    the example-shibboleth2.xml\n    file, and the https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPRequestMapHowTo
    topic.\n    -->\n    <TCPListener address=\"127.0.0.1\" port=\"1600\"/> \n\n\n
    \   <!-- The ApplicationDefaults element is where most of Shibboleth's SAML bits
    are defined. -->\n    <ApplicationDefaults entityID=\"https://grouperdemo/shibboleth\"\n
    \                        REMOTE_USER=\"uid\">\n\n        <!--\n        Controls
    session lifetimes, address checks, cookie handling, and the protocol handlers.\n
    \       You MUST supply an effectively unique handlerURL value for each of your
    applications.\n        The value defaults to /Shibboleth.sso, and should be a
    relative path, with the SP computing\n        a relative value based on the virtual
    host. Using handlerSSL=\"true\", the default, will force\n        the protocol
    to be https. You should also set cookieProps to \"https\" for SSL-only sites.\n
    \       Note that while we default checkAddress to \"false\", this has a negative
    impact on the\n        security of your site. Stealing sessions via cookie theft
    is much easier with this disabled.\n        -->\n        <Sessions lifetime=\"28800\"
    timeout=\"28800\" relayState=\"ss:mem\"\n                  checkAddress=\"false\"
    handlerSSL=\"true\" cookieProps=\"https\">\n\n            <!--\n            Configures
    SSO for a default IdP. To allow for >1 IdP, remove\n            entityID property
    and adjust discoveryURL to point to discovery service.\n            (Set discoveryProtocol
    to \"WAYF\" for legacy Shibboleth WAYF support.)\n            You can also override
    entityID on /Login query string, or in RequestMap/htaccess.\n            -->\n\t\t<SSO
    entityID=\"https://idptestbed/idp/shibboleth\">\n\t\t\tSAML2\n\t\t</SSO>\n\n            <!--
    SAML and local-only logout. -->\n            <Logout>SAML2 Local</Logout>\n            \n
    \           <!-- Extension service that generates \"approximate\" metadata based
    on SP configuration. -->\n            <Handler type=\"MetadataGenerator\" Location=\"/Metadata\"
    signing=\"false\"/>\n\n            <!-- Status reporting service. -->\n            <Handler
    type=\"Status\" Location=\"/Status\" acl=\"127.0.0.1 ::1\"/>\n\n            <!--
    Session diagnostic service. -->\n            <Handler type=\"Session\" Location=\"/Session\"
    showAttributeValues=\"true\"/>\n\n            <!-- JSON feed of discovery information.
    -->\n            <Handler type=\"DiscoveryFeed\" Location=\"/DiscoFeed\"/>\n        </Sessions>\n\n
    \       <!--\n        Allows overriding of error template information/filenames.
    You can\n        also add attributes with values that can be plugged into the
    templates.\n        -->\n        <Errors supportContact=\"root@localhost\"\n            helpLocation=\"/about.html\"\n
    \           styleSheet=\"/shibboleth-sp/main.css\"/>\n        \n        <!-- Example
    of remotely supplied batch of signed metadata. -->\n        <!--\n        <MetadataProvider
    type=\"XML\" validate=\"true\"\n\t      uri=\"http://example.org/federation-metadata.xml\"\n
    \             backingFilePath=\"federation-metadata.xml\" reloadInterval=\"7200\">\n
    \           <MetadataFilter type=\"RequireValidUntil\" maxValidityInterval=\"2419200\"/>\n
    \           <MetadataFilter type=\"Signature\" certificate=\"fedsigner.pem\"/>\n
    \           <DiscoveryFilter type=\"Blacklist\" matcher=\"EntityAttributes\" trimTags=\"true\"
    \n              attributeName=\"http://macedir.org/entity-category\"\n              attributeNameFormat=\"urn:oasis:names:tc:SAML:2.0:attrname-format:uri\"\n
    \             attributeValue=\"http://refeds.org/category/hide-from-discovery\"
    />\n        </MetadataProvider>\n        -->\n\n        <MetadataProvider type=\"XML\"
    validate=\"true\" file=\"idp-metadata.xml\"/>\n\n        <!--\n        InCommon\n\t
    \ <MetadataProvider type=\"XML\" validate=\"true\"\n\t\turi=\"http://md.incommon.org/InCommon/InCommon-metadata.xml\"\n
    \             backingFilePath=\"federation-metadata.xml\" reloadInterval=\"7200\">\n
    \           <MetadataFilter type=\"RequireValidUntil\" maxValidityInterval=\"2419200\"/>\n\t\t<MetdataFilter
    type=\"Signature\" certificate=\"inc-md-cert.pem\"/>\n            <DiscoveryFilter
    type=\"Blacklist\" matcher=\"EntityAttributes\" trimTags=\"true\" \n              attributeName=\"http://macedir.org/entity-category\"\n
    \             attributeNameFormat=\"urn:oasis:names:tc:SAML:2.0:attrname-format:uri\"\n
    \             attributeValue=\"http://refeds.org/category/hide-from-discovery\"
    />\n        </MetadataProvider>\n        -->\n\n        <!-- Map to extract attributes
    from SAML assertions. -->\n        <AttributeExtractor type=\"XML\" validate=\"true\"
    reloadChanges=\"false\" path=\"attribute-map.xml\"/>\n        \n        <!-- Use
    a SAML query if no attributes are supplied during SSO. -->\n        <AttributeResolver
    type=\"Query\" subjectMatch=\"true\"/>\n\n        <!-- Default filtering policy
    for recognized attributes, lets other data pass. -->\n        <AttributeFilter
    type=\"XML\" validate=\"true\" path=\"attribute-policy.xml\"/>\n\n        <!--
    Simple file-based resolver for using a single keypair. -->\n        <CredentialResolver
    type=\"File\" key=\"sp-key.pem\" certificate=\"sp-cert.pem\"/>\n\n        <!--\n
    \       The default settings can be overridden by creating ApplicationOverride
    elements (see\n        the https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPApplicationOverride
    topic).\n        Resource requests are mapped by web server commands, or the RequestMapper,
    to an\n        applicationId setting.\n        \n        Example of a second application
    (for a second vhost) that has a different entityID.\n        Resources on the
    vhost would map to an applicationId of \"admin\":\n        -->\n        <!--\n
    \       <ApplicationOverride id=\"admin\" entityID=\"https://admin.example.org/shibboleth\"/>\n
    \       -->\n    </ApplicationDefaults>\n    \n    <!-- Policies that determine
    how to process and authenticate runtime messages. -->\n    <SecurityPolicyProvider
    type=\"XML\" validate=\"true\" path=\"security-policy.xml\"/>\n\n    <!-- Low-level
    configuration about protocols and bindings available for use. -->\n    <ProtocolProvider
    type=\"XML\" validate=\"true\" reloadChanges=\"false\" path=\"protocols.xml\"/>\n\n</SPConfig>\n"
kind: ConfigMap
metadata:
  name: shibboleth2
  namespace: test
# immutable: true